### ISSUE TITLE
not support rails 4

### ISSUE THREAD

**Issue by x1wins** [amatsuda/nested_scaffold#11]
i use rails 4.1 or 4.0

but nested_scaffold gem maybe support rails 3.2.2

i want nested_scaffold support rails 4

**Comment by hackerwins** [comment]
same here...

**Comment by ryanckulp** [comment]
@hackerwins / @x1wins hey guys, simple workaround is to simply VIM into the offending file (stylesheet generator) and remove the 'require' line.

Here's an example on my machine:

```cd /Users/YOUR_USER_NAME/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/nested_scaffold-0.1.0/lib/generators/stylesheets```

Obviously you may not use rbenv, etc but the exact path will show up in the stack trace when you try to run the nested_scaffold command on a rails 4 app.

Simply go into the file and neutralize the content so it looks like this:

```module NestedScaffold
  module Generators
  end
end```

**Comment by amatsuda** [comment]
This gem supports Rails 4.2 and 5.0 now. Thanks!
